In [5]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Using cached pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.8 MB 8.3 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.8 MB 18.7 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 21.8 MB/s eta 0:00:00
Installing collected packages: pandas
Successfully installed pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 429.7 kB/s eta 0:00:22
   -- ------------------------------------- 0.5/9.8 MB 429.7 kB/s eta 0:00:22
   -- ------------------------------------- 0.5/9.8 MB 429.7 kB/s eta 0:00:22
   -- ------------------------------------- 0.5/9.8 MB 429.7 kB/s eta 0:00:22
   -- ------------------------------------- 0.5/9.8 MB 429.7 kB/s eta 0:00:22
   -- ------------------------------------- 0.5/9.8 MB 429.7 kB/s eta 0:00:22
   --- ------------------------------------ 0.8/9.8 MB 277.3 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 277.3 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 277.3 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 277.3 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 277.3 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 277.3 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 277.3 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 277.3 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 277.3 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 277.3 kB/s eta 0:00:33
   --- ------------------------------------ 0.8/9.8 MB 277.3 kB/s eta 0:00:33
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.0/9.8 MB 191.3 kB/s eta 0:00:46
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ----- ---------------------------------- 1.3/9.8 MB 138.9 kB/s eta 0:01:02
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------ --------------------------------- 1.6/9.8 MB 109.1 kB/s eta 0:01:16
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   ------- -------------------------------- 1.8/9.8 MB 89.5 kB/s eta 0:01:30
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   -------- ------------------------------- 2.1/9.8 MB 78.0 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   --------- ------------------------------ 2.4/9.8 MB 75.1 kB/s eta 0:01:40
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ---------- ----------------------------- 2.6/9.8 MB 70.2 kB/s eta 0:01:43
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ----------- ---------------------------- 2.9/9.8 MB 63.5 kB/s eta 0:01:50
   ------------ --------------------------- 3.1/9.8 MB 63.3 kB/s eta 0:01:46
   ------------ --------------------------- 3.1/9.8 MB 63.3 kB/s eta 0:01:46
   ------------ --------------------------- 3.1/9.8 MB 63.3 kB/s eta 0:01:46
   ------------ --------------------------- 3.1/9.8 MB 63.3 kB/s eta 0:01:46
   ------------ --------------------------- 3.1/9.8 MB 63.3 kB/s eta 0:01:46
   ------------ --------------------------- 3.1/9.8 MB 63.3 kB/s eta 0:01:46
   ------------ --------------------------- 3.1/9.8 MB 63.3 kB/s eta 0:01:46
   ------------ --------------------------- 3.1/9.8 MB 63.3 kB/s eta 0:01:46
   ------------ --------------------------- 3.1/9.8 MB 63.3 kB/s eta 0:01:46
   ------------- -------------------------- 3.4/9.8 MB 70.0 kB/s eta 0:01:32
   ------------- -------------------------- 3.4/9.8 MB 70.0 kB/s eta 0:01:32
   ------------- -------------------------- 3.4/9.8 MB 70.0 kB/s eta 0:01:32
   ------------- -------------------------- 3.4/9.8 MB 70.0 kB/s eta 0:01:32
   ------------- -------------------------- 3.4/9.8 MB 70.0 kB/s eta 0:01:32
   ------------- -------------------------- 3.4/9.8 MB 70.0 kB/s eta 0:01:32
   ------------- -------------------------- 3.4/9.8 MB 70.0 kB/s eta 0:01:32
   ------------- -------------------------- 3.4/9.8 MB 70.0 kB/s eta 0:01:32
   ------------- -------------------------- 3.4/9.8 MB 70.0 kB/s eta 0:01:32
   ------------- -------------------------- 3.4/9.8 MB 70.0 kB/s eta 0:01:32
   ------------- -------------------------- 3.4/9.8 MB 70.0 kB/s eta 0:01:32
   -------------- ------------------------- 3.7/9.8 MB 73.6 kB/s eta 0:01:24
   -------------- ------------------------- 3.7/9.8 MB 73.6 kB/s eta 0:01:24
   -------------- ------------------------- 3.7/9.8 MB 73.6 kB/s eta 0:01:24
   -------------- ------------------------- 3.7/9.8 MB 73.6 kB/s eta 0:01:24
   -------------- ------------------------- 3.7/9.8 MB 73.6 kB/s eta 0:01:24
   -------------- ------------------------- 3.7/9.8 MB 73.6 kB/s eta 0:01:24
   -------------- ------------------------- 3.7/9.8 MB 73.6 kB/s eta 0:01:24
   -------------- ------------------------- 3.7/9.8 MB 73.6 kB/s eta 0:01:24
   -------------- ------------------------- 3.7/9.8 MB 73.6 kB/s eta 0:01:24
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   --------------- ------------------------ 3.9/9.8 MB 84.7 kB/s eta 0:01:10
   ----------------- ---------------------- 4.2/9.8 MB 82.3 kB/s eta 0:01:09
   ----------------- ---------------------- 4.2/9.8 MB 82.3 kB/s eta 0:01:09
   ----------------- ---------------------- 4.2/9.8 MB 82.3 kB/s eta 0:01:09
   ----------------- ---------------------- 4.2/9.8 MB 82.3 kB/s eta 0:01:09
   ----------------- ---------------------- 4.2/9.8 MB 82.3 kB/s eta 0:01:09
   ----------------- ---------------------- 4.2/9.8 MB 82.3 kB/s eta 0:01:09
   ----------------- ---------------------- 4.2/9.8 MB 82.3 kB/s eta 0:01:09
   ----------------- ---------------------- 4.2/9.8 MB 82.3 kB/s eta 0:01:09
   ----------------- ---------------------- 4.2/9.8 MB 82.3 kB/s eta 0:01:09
   ----------------- ---------------------- 4.2/9.8 MB 82.3 kB/s eta 0:01:09
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57
   ------------------ --------------------- 4.5/9.8 MB 95.4 kB/s eta 0:00:57

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [6]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [9]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)' : 'purchase_amount'})

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [12]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [13]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [14]:
df['age_group'].value_counts()

age_group
Young Adult    1028
Middle-aged     986
Senior          944
Adult           942
Name: count, dtype: int64

In [15]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [16]:
df[['purchase_frequency_days','frequency_of_purchases']].head(5)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually

In [17]:
df['purchase_frequency_days'].isnull().sum()

np.int64(0)

In [18]:
df['frequency_of_purchases'].unique()

<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [19]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [20]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [21]:
df = df.drop('promo_code_used', axis = 1)

In [22]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [23]:
!pip install pyodbc sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in c:\users\lenovo\appdata\roaming\python\python312\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\lenovo\appdata\roaming\python\python312\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from sqlalchemy) (4.16.0)

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import pandas as pd

# 1. Cấu hình kết nối bằng Windows Authentication (Không cần mật khẩu)
host = "localhost" 
database = "customer_behavior"
driver = quote_plus("ODBC Driver 17 for SQL Server")

# Chuỗi kết nối đã thêm Trusted_Connection=yes
engine = create_engine(f"mssql+pyodbc://{host}/{database}?driver={driver}&Trusted_Connection=yes")

table_name = "customer"

# 2. Vận chuyển dữ liệu
print("Đang vận chuyển dữ liệu vào SQL Server...")
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Thành công! Đã đổ dữ liệu vào bảng '{table_name}'.")

# 3. Kiểm tra xem SQL đã nhận được hàng chưa
print("\n--- Bản xem trước 5 dòng từ SQL Server ---")
check_df = pd.read_sql("SELECT TOP 5 * FROM customer;", engine)
check_df

Đang vận chuyển dữ liệu vào SQL Server...
Thành công! Đã đổ dữ liệu vào bảng 'customer'.

--- Bản xem trước 5 dòng từ SQL Server ---

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365